name: components
channels:
  - conda-forge
  - defaults
dependencies:
#  - python=3.8
  - python=3.9.15
  - mlflow=1.14.1
  - pyyaml=5.4.1
  - pip=21.1.1
  - pip:
      - hydra-core==1.0.6
     # - wandb==0.10.30
      - wandb==0.16.0
      - numpy==1.23.5

