name: components
channels:
  - conda-forge
  - defaults
dependencies:
#  - python=3.8
  - python=3.9.15
  #- mlflow=1.14.1
  - mlflow=2.1.1
  #- pyyaml=5.4.1
  - pyyaml=5.3.1
  #- pip=21.1.1
  ## add these
  - hydra-core=1.0.6
  - pip=20.3.3
  - pip:
      - hydra-core==1.0.6
     # - wandb==0.10.30
      - wandb==0.13.9
      - numpy==1.23.5
      - databricks_cli==0.8.7

